### ISSUE TITLE
Nightly Arrow tests are failing because of datafusion.substrait no longer being available

### ISSUE THREAD

**Issue by jorisvandenbossche** [substrait-io/consumer-testing#36]
The arrow nightly build with substrait integration tests is currently failing because of a datafusion import problem ([latest logs](https://github.com/ursacomputing/crossbow/actions/runs/7054007428/job/19202127435)):

```
Substrait Integration Tests
Validating imports
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/arrow/lib/python3.10/site-packages/substrait_consumer-0.0.1-py3.10.egg/substrait_consumer/consumers.py", line 13, in <module>
    from datafusion import substrait as ds
  File "/opt/conda/envs/arrow/lib/python3.10/site-packages/datafusion/substrait.py", line 19, in <module>
    from ._internal import substrait
ImportError: cannot import name 'substrait' from 'datafusion._internal' (/opt/conda/envs/arrow/lib/python3.10/site-packages/datafusion/_internal.abi3.so)
1
```

I think this might be caused by https://github.com/apache/arrow-datafusion-python/pull/527, which appeared in datafusion 33.0. 
(short term workaround to get the tests green again might be to pin datafusion to 32.0)

**Comment by jdye64** [comment]
> `pip install datafusion` (from the requirements.txt here).

Sorry I can't seem to find that while grepping the codebase? Am I overlooking something? Can you point me to the code snippet performing that pip install datafusion? I just made a PR to Arrow DataFusion Python to include substrait in the nightly builds and if that command is pulling from the nightlies that should hopefully help out.

I opened a PR https://github.com/apache/arrow-datafusion-python/pull/544 where we can at least start to understand if that will help this issue or not and discuss there.

**Comment by richtia** [comment]
Thanks for pointing this out @jorisvandenbossche! I completely forgot that the arrow nightlies used the dependencies in this repo.  I had seen this issue last week, but only did the [pinning in CI here](https://github.com/substrait-io/consumer-testing/blob/main/ci/docker/datafusion_consumer.Dockerfile#L6).  I'll push the pinning in the requirements.txt too.
